from datetime import datetime

def print_report(data, ai_insights):
    separator = "=" * 60

    print(f"\n{separator}")
    print(f"  📊 GITHUB PROFILE ANALYSIS REPORT")
    print(f"  Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print(f"{separator}\n")

    print(f"👤 Username   : {data['username']}")
    print(f"📛 Name       : {data['name']}")
    print(f"📝 Bio        : {data['bio']}")
    print(f"📦 Public Repos: {data['public_repos']}")
    print(f"👥 Followers  : {data['followers']}")
    print(f"⭐ Total Stars : {data['total_stars']}")

    print(f"\n💻 Top Languages:")
    for lang, count in list(data["top_languages"].items())[:5]:
        print(f"   - {lang}: {count} repo(s)")

    print(f"\n🗂️  Recent Repositories:")
    for repo in data["repos"]:
        print(f"   - {repo['name']} [{repo['language']}] ⭐{repo['stars']}")
        print(f"     {repo['description']}")
        print(f"     🔗 {repo['url']}")

    print(f"\n{separator}")
    print(f"  🤖 AI INSIGHTS (Powered by Gemini)")
    print(f"{separator}\n")
    print(ai_insights)
    print(f"\n{separator}\n")


def save_report(data, ai_insights, filename=None):
    if not filename:
        filename = f"report_{data['username']}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"

    separator = "=" * 60

    content = f"""# 📊 GitHub Profile Analysis Report
**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

---

## 👤 Profile Overview

| Field | Value |
|-------|-------|
| Username | {data['username']} |
| Name | {data['name']} |
| Bio | {data['bio']} |
| Public Repos | {data['public_repos']} |
| Followers | {data['followers']} |
| Total Stars | {data['total_stars']} |

## 💻 Top Languages

{chr(10).join([f"- **{lang}**: {count} repo(s)" for lang, count in list(data['top_languages'].items())[:5]])}

## 🗂️ Recent Repositories

{chr(10).join([f"- [{r['name']}]({r['url']}) `{r['language']}` ⭐{r['stars']} — {r['description']}" for r in data['repos']])}

---

## 🤖 AI Insights (Powered by Gemini)

{ai_insights}

---
*Report generated by [github-ai-analyzer](https://github.com/your-username/github-ai-analyzer)*
"""

    with open(filename, "w") as f:
        f.write(content)

    print(f"✅ Report saved as: {filename}")
    return filename
